export const Size = (width, height) => ({width, height})
export const Point = (x, y) => ({x, y})
export const BoardSize = (rows, cols) => ({rows, cols})
export const Space = (row, col) => ({row, col})
export const UnitPos = (row, col, i) => ({row, col, i})
